- hosts: localhost
  gather_facts: no
  vars:
    docker_volume: db_data
    docker_network: ansible_net
    db_name: db
    wp_name: wordpress
    wp_host_port: 8000
    wp_container_port: 80

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: "Create a Volume"
      docker_volume:
        name: "{{ docker_volume }}"
    - name: "Create a network"
      docker_network:
        name: "{{ docker_network }}"
    - name: "Launch database container"
      docker_container:
        name: "{{ db_name }}"
        image: mysql:5.7
        volumes:
          - "{{ docker_volume }}:/var/lib/mysql:rw"
        restart: true
	networks:
          - name: "{{ docker_network }}"
            alias:
              - "{{ db_name }}"
        env:
          MYSQL_ROOT_PASSWORD: wordpress
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
    - name: "Launch wordpress container"
      docker_container:
        name: "{{ wp_name }}"
        image: mediawiki:latest
        ports:
          - "{{ wp_host_port }}:{{ wp_container_port }}"
        restart: true
